podcasts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'podcasts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index', views.IndexView.as_view(), name='index'),
    path('downloaded', views.DownloadedView.as_view(), name='downloaded'),
    path('test', views.TestView.as_view(), name='test'),
    url('delete', views.delete, name='delete'),
]

pystuff/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('podcasts/', include('podcasts.urls')),
    path('',include('django_prometheus.urls')),
]

podcasts/models.py
from django.db import models

# Create your models here.


class Podcast(models.Model):
    PODCAST_STATUS = (
        (0, 'None'),
        (1, 'WillDownload'),
        (2, 'Downloading'),
        (3, 'Downloaded'),
        (4, 'Error'),
        (5, 'Deleted'),
    )
    Title = models.CharField(max_length=200)
    Summary = models.CharField(max_length=2048)
    # 原始下载地址
    Link = models.CharField(max_length=512)
    # 本地服务器镜像
    MirrorLink = models.CharField(max_length=200)
    PublishDate = models.DateTimeField('date published')
    Status = models.IntegerField(default=0, choices=PODCAST_STATUS)
    Location = models.CharField(max_length=200, null=True, blank=True)
    Remark = models.CharField(max_length=2048, null=True, blank=True)

podcasts/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render
from django.views import generic
from django.db.models import Q

from .models import Podcast

import os
import logging

logger = logging.getLogger('pystuff')

class IndexView(generic.ListView):
    template_name = 'podcasts/index.html'
    context_object_name = 'latest_podcasts_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Podcast.objects.order_by('-PublishDate')[:100]
        
    def post(self, request):
        try:
            data = request.POST['ids']
            ids = data.split(',')
            Podcast.objects.filter(pk__in=ids).filter(~Q(Status=3)).update(Status=1)
            return HttpResponse("ok")
        except Exception:
            return HttpResponse("error")

class DownloadedView(generic.ListView):
    template_name = 'podcasts/downloaded.html'
    context_object_name = 'latest_podcasts_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Podcast.objects.filter(Status=3).order_by('-PublishDate')[:100]

class TestView(generic.ListView):
    template_name = 'podcasts/test.html'
    context_object_name = 'latest_podcasts_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Podcast.objects.filter(Status=3).order_by('-PublishDate')[:10]

def delete(request):
    try:
        title = request.POST['title']
        podcast = Podcast.objects.get(Title=title)
        fileDir = os.path.join(os.getcwd(),podcast.Location)
        if os.path.exists(fileDir):
            os.remove(fileDir)
        podcast.Status = 5
        podcast.save()
        return HttpResponse("ok")
    except Exception:
        return HttpResponse("error")

podcasts/templates/podcasts/downloaded.html
{% extends 'share.html' %} {% block podcasts_list %}
<div id="musicBar" class="container rounded-top">
    <div class="row">
        <div class="col-11" style="color:#FFF">
            <p id='nowPlaying'>Summary</p>
        </div>
    </div>
    <div class="row">
        <audio controls="controls" id="musicPlayer">
            Your browser does not support this audio format.
        </audio>
    </div>
</div>
<div id="tablePodcast" class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Sumarry</th>
        <th scope="col">Release</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for podcast in latest_podcasts_list %}
      <tr>
        <td>{{ podcast.Title }}</td>
        <td>
          <div>{{ podcast.Summary | safe }}</div>
        </td>
        <td>{{ podcast.PublishDate }}</td>
        <td>
          <div class="btn-group">
            <button class="btn btn-success btnPlay" value="{{ podcast.MirrorLink }}" title="{{ podcast.Title }}">
              播放
            </button>
            <a class="btn btn-primary" href="{{ podcast.MirrorLink }}">下载</a>
            <button
              class="btn btn-danger btnDelete" data-toggle="modal" data-target="#exampleModalCenter"
              value="{{ podcast.Title }}"
            >
              删除
            </button>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Are you sure to delete?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            ...
        </div>
        <div class="modal-footer">
            <button id='btnDeleteConfirm' type="button" class="btn btn-danger">Delete</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $.ajaxSetup({
            data: { csrfmiddlewaretoken: "{{ csrf_token }}" }
        });
        $("#musicBar").hide()

        $(".btnPlay").click(function () {
            $("#musicBar").show()
            const title = $(this).attr('title')
            $('#nowPlaying').text(title)
            
            const link = $(this).val();
            $("#musicPlayer").prop("src", link);
            $("#musicPlayer")[0].play();
        });

        $(".btnDelete").click(function () {
            const title = $(this).val();
            $('.modal-body').text(title)
            $("#btnDeleteConfirm").click(function () {
                $.post("delete", { title: title }, data => {
                    console.log(`post download result: ${data}`);
                    if (data === "ok") {
                        window.location.reload();
                    }
                });
            });
        });
    });
</script>
{% endblock %} {% block status_message %} {% endblock %}

podcasts/templates/podcasts/index.html
{% extends 'share.html' %}
{% block podcasts_list %}
<div>
    <button id='btnDownload' class="btn btn-primary" disabled="disabled">Download</button>
</div>
<div id='tablePodcast' class="table-responsive">
    <form action="{% url 'podcasts:index' %}" method="post">
        {% csrf_token %}
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">
                        <div class="form-check">
                            <input class="form-check-input position-static chkDownload-all" type="checkbox" id="wpz" value="option1"
                                aria-label="...">
                        </div>
                    </th>
                    <th scope="col">Title</th>
                    <th scope="col">Release</th>
                </tr>
            </thead>    
            <tbody>
                {% for podcast in latest_podcasts_list %}
                <tr {% if podcast.Status == 3 %}
                        class="table-success"
                    {% elif podcast.Status == 1 %}
                        class="table-warning"
                    {% endif %}>
                    <th>
                        {% if podcast.Status != 3 and podcast.Status != 1 and podcast.Status != 2 %}
                        <div class="form-check">
                            <input class="form-check-input position-static chkDownload" type="checkbox" id={{podcast.id}} value="option1"
                                aria-label="...">
                        </div>
                        {% endif %}
                    </th>
                    <td>
                        <a tabindex="0" data-toggle="popover" data-trigger="focus" title="Detail" 
                        data-content="{{ podcast.Summary }}" data-html=true>{{ podcast.Title }}</a>
                    </td>
                    <td>{{ podcast.PublishDate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>

<script>
    const setDownloadBtnStatus = () => {
        const count = $("input:checkbox:checked").length
        $('#btnDownload').attr("disabled", count < 1)
        //$('#btnDownload').show()
        $('#btnDownload').text(`Download ${count} file${count > 1 ? 's' : ''}`)
    }

    const clearCheckFile = () => {
        $(".chkDownload-all").prop("checked", false);
        $(".chkDownload").prop("checked", false);
    }

    $(function () {
        $.ajaxSetup({
            data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
        })
        clearCheckFile();
        setDownloadBtnStatus();

        $(".chkDownload").click(() => {
            const uncheckCount = $(".chkDownload:not(:checked)").length
            const checkCount = $(".chkDownload:checked").length
            $(".chkDownload-all").prop("checked", uncheckCount == 0);

            setDownloadBtnStatus()
        })

        $(".chkDownload-all").click(() => {
            const uncheckCount = $(".chkDownload:not(:checked)").length
            const checkCount = $(".chkDownload:checked").length
            if (checkCount == 0) {
                $(".chkDownload").prop("checked", true);
            }
            else if (uncheckCount == 0) {
                $(".chkDownload").prop("checked", false);
            }
            else {
                $(".chkDownload").prop("checked", true);
            }

            setDownloadBtnStatus()
        })

        $("#btnDownload").click(() => {
            const id_array = []
            $(".chkDownload:checked").each(function () {
                id_array.push($(this).attr('id'));
            }
            )
            const ids = id_array.join(',');
            $.post("", { "ids": ids }, (data) => {
                console.log(`post download result: ${data}`)
                if (data === 'ok') {
                    window.location.reload()
                }
            });
        })

        $('.popover-dismiss').popover({
            trigger: 'focus'
        })

    })
</script>
{% endblock %}

{% block status_message %}
 can you see me?
{% endblock %}

podcasts/templates/podcasts/test.html
{% extends 'share.html' %}
{% block podcasts_list %}
{% load static %}
<style type="text/css">
    #container-fluid {
        margin: 56px 0;
    }

    #qqmap {
        width: 100%;
        min-height: 800px;
    }
</style>
<script charset="utf-8" src="https://map.qq.com/api/js?v=2.exp&key=QQQBZ-RYMLS-NZDOA-6WUG7-UYTOE-TSFMX"></script>
<script src="{% static "js/echarts.js" %}"></script>
<script src="{% static "js/myfunc.js" %}"></script>

<div id="container-fluid">
    <div class="row">
        <!--
        <div id="leftResult" class="col-xl-2">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
        </div>
        -->
        <div class="col-xl-9">
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" name="options" id="option1" autocomplete="off" checked> Map
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="options" id="option3" autocomplete="off"> Wave
                </label>
            </div>
            <div id="qqmap"></div>
            <canvas id="mycanvas" style="border: 1px solid red;" width="1300px" height="800px" hidden="true">
                    您的浏览器不支持canvas标签。
            </canvas>
        </div>
        <div class="col-xl-3">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary" type="button" id="inputGroupFileAddon03">Upload</button>
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03">
                    <label class="custom-file-label" for="inputGroupFile03">Choose file</label>
                </div>
            </div>
            <ul id="rightResult" class="list-group list-group-flush">
                <li class="list-group-item">搜索结果...</li>
            </ul>
        </div>
    </div>
</div>
<script>
    $(function () {
        takeOverSearch();
        setContentSwitch();
        initChart();
        setUploadFile();
        let mimi = initMap()
        console.log("document ok")
    })
    window.onload = function(){
        console.log("window ok")
    };
    $("li[href='abc']").each(function () {
        console.log(this.innerText)
    });
</script>
{% endblock %}

podcasts/templates/share.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Python Podcasts</title>
    {% load static %}
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.js" %}"></script>
    <style type="text/css">
        #tablePodcast {margin: 56px 0}
        #btnDownload{
            position: fixed;
            margin-top: 4px;
            right: 64px;
        }   
        #musicBar {
            position: fixed;
            bottom: 4px;
            background-color: rgba(128, 128, 128, 0.8);
        }        
        #musicPlayer {
            width: 100%;
        }
        .footer {
            bottom: 0;
            width: 100%;
            height: 60px; /* Set the fixed height of the footer here */
            line-height: 60px; /* Vertically center the text there */
            background-color: #f5f5f5;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Stuff You Should Know</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="downloaded">Downloaded</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input id="txtSearchAll" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button id="btnSearchAll" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <main class="container-fluid" role="main">
        {% block podcasts_list %}
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="container">
            <span class="text-muted">
                {% block status_message %}
                {% endblock %}
            </span>
        </div>
    </footer>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
</body>

</html>